events {}

http{
    include mime.types;
    server{
        listen 8000;
        root /usr/share/nginx/html;
        index index.html

        location /mascosas {
            alias /usr/share/nginx/html/miscosas;
        }
        # etcétera etcétera
   }
}